name: Test and Build üòé

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
        - ./
        unityVersion:
          - 2019.4.2f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # Build a HTML playable in browser
    steps:
      # Checkout
      - name: Checkout repository ‚§µÔ∏è
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - name: Cache library üíæ
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      # Test
      - name: Run tests üíØ
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.4.2f1

      # Build
      - name: Build project üöß
        uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - name: Upload build ‚§¥Ô∏è
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
          # ls ./build --> StandaloneOSX/ StandaloneWindows64/ ... WebGL

  deploy:
    name: Deploy Apps to itch.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download builds ‚§µÔ∏è
        uses: actions/download-artifact@v1
        with:
          name: Build
      - name: list dir
        run: ls ./*
      # Deploy HTML to Itch (NOTE: will need to activate this on itchio)
      # https://itch.io/t/47990/how-to-use-butler-for-html-games
      - name: Deploy HTML build to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: unity-template
          ITCH_USER: avivajpeyi
          PACKAGE: Build/build/WebGL

      # Deploy osx to Itch
      - name: Deploy OSX app to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: unity-template
          ITCH_USER: avivajpeyi
          PACKAGE: Build/build/StandaloneOSX

      # Deploy windows to Itch
      - name: Deploy windows app to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: unity-template
          ITCH_USER: avivajpeyi
          PACKAGE: Build/build/StandaloneWindows64

        # Deploy windows to Itch
      - name: Deploy linux app to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: unity-template
          ITCH_USER: avivajpeyi
          PACKAGE: Build/build/StandaloneLinux64
