name: Test and Build ğŸ˜

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Test + Build my project âœ¨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository â¤µï¸
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - name: Cache library ğŸ’¾
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests ğŸ’¯
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.4.2f1

      # Build
      - name: Build project ğŸš§
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.2f1
          targetPlatform: WebGL 

      # Output 
      - name: Upload build â¤´ï¸
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
